### ISSUE TITLE
Typo in Providers.tsx

### ISSUE THREAD

**Issue by nacholupotti** [NdungutseCharles103/next13-progressbar#4]
Bro there is a typo in Providers.tsx. The "return" and the next line are written twice.

The correct file should be:

'use client';
import React from 'react';
import { Next13ProgressBar } from 'next13-progressbar';

const Providers = ({ children }: { children: React.ReactNode }) => {
  return (
    <>
        {children}
        <Next13ProgressBar height="4px" color="#0A2FFF" options={{ showSpinner: true }} showOnShallow />
    </>
    );
};

export default Providers;

By the way, thanks for the library! very useful. Big hug from Argentina

**Comment by NdungutseCharles103** [comment]
Oh, right. That true there is a typo. Thanks for your vision. Big hug too we love Argentinians and the G.O.A.T Messi 😍
